package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="techguy"
)
public class Admin  implements java.io.Serializable {


     private Integer admId;
     private String userName;
     private String email;
     private String addressLineOne;
     private String addresslineTwo;
     private String city;
     private String cityCode;
     private String province;
     private String telephone;
     private String password;
     private String proPicture;
     private String gender;
     private Set<Interview> interviews = new HashSet<Interview>(0);

    public Admin() {
    }

	
    public Admin(String userName, String password) {
        this.userName = userName;
        this.password = password;
    }
    public Admin(String userName, String email, String addressLineOne, String addresslineTwo, String city, String cityCode, String province, String telephone, String password, String proPicture, String gender, Set<Interview> interviews) {
       this.userName = userName;
       this.email = email;
       this.addressLineOne = addressLineOne;
       this.addresslineTwo = addresslineTwo;
       this.city = city;
       this.cityCode = cityCode;
       this.province = province;
       this.telephone = telephone;
       this.password = password;
       this.proPicture = proPicture;
       this.gender = gender;
       this.interviews = interviews;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="admId", unique=true, nullable=false)
    public Integer getAdmId() {
        return this.admId;
    }
    
    public void setAdmId(Integer admId) {
        this.admId = admId;
    }

    
    @Column(name="userName", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="addressLineOne", length=45)
    public String getAddressLineOne() {
        return this.addressLineOne;
    }
    
    public void setAddressLineOne(String addressLineOne) {
        this.addressLineOne = addressLineOne;
    }

    
    @Column(name="addresslineTwo", length=45)
    public String getAddresslineTwo() {
        return this.addresslineTwo;
    }
    
    public void setAddresslineTwo(String addresslineTwo) {
        this.addresslineTwo = addresslineTwo;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="cityCode", length=20)
    public String getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    
    @Column(name="province", length=45)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    
    @Column(name="telephone", length=45)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="password", nullable=false, length=80)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="proPicture", length=100)
    public String getProPicture() {
        return this.proPicture;
    }
    
    public void setProPicture(String proPicture) {
        this.proPicture = proPicture;
    }

    
    @Column(name="gender", length=6)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="admin")
    public Set<Interview> getInterviews() {
        return this.interviews;
    }
    
    public void setInterviews(Set<Interview> interviews) {
        this.interviews = interviews;
    }

}


