package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CompanyHasJobroleId generated by hbm2java
 */
@Embeddable
public class CompanyHasJobroleId  implements java.io.Serializable {


     private int companyCompanyId;
     private int jobRoleJobRoleId;

    public CompanyHasJobroleId() {
    }

    public CompanyHasJobroleId(int companyCompanyId, int jobRoleJobRoleId) {
       this.companyCompanyId = companyCompanyId;
       this.jobRoleJobRoleId = jobRoleJobRoleId;
    }
   


    @Column(name="Company_companyId", nullable=false)
    public int getCompanyCompanyId() {
        return this.companyCompanyId;
    }
    
    public void setCompanyCompanyId(int companyCompanyId) {
        this.companyCompanyId = companyCompanyId;
    }


    @Column(name="JobRole_jobRoleId", nullable=false)
    public int getJobRoleJobRoleId() {
        return this.jobRoleJobRoleId;
    }
    
    public void setJobRoleJobRoleId(int jobRoleJobRoleId) {
        this.jobRoleJobRoleId = jobRoleJobRoleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompanyHasJobroleId) ) return false;
		 CompanyHasJobroleId castOther = ( CompanyHasJobroleId ) other; 
         
		 return (this.getCompanyCompanyId()==castOther.getCompanyCompanyId())
 && (this.getJobRoleJobRoleId()==castOther.getJobRoleJobRoleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCompanyCompanyId();
         result = 37 * result + this.getJobRoleJobRoleId();
         return result;
   }   


}


