package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name="company"
    ,catalog="techguy"
)
public class Company  implements java.io.Serializable {


     private int companyId;
     private String name;
     private String description;
     private String location;
     private String latitude;
     private String altitude;
     private String founder;
     private Set<User> users = new HashSet<User>(0);
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<CompanyHasJobrole> companyHasJobroles = new HashSet<CompanyHasJobrole>(0);

    public Company() {
    }

	
    public Company(int companyId) {
        this.companyId = companyId;
    }
    public Company(int companyId, String name, String description, String location, String latitude, String altitude, String founder, Set<User> users, Set<Review> reviews, Set<CompanyHasJobrole> companyHasJobroles) {
       this.companyId = companyId;
       this.name = name;
       this.description = description;
       this.location = location;
       this.latitude = latitude;
       this.altitude = altitude;
       this.founder = founder;
       this.users = users;
       this.reviews = reviews;
       this.companyHasJobroles = companyHasJobroles;
    }
   
     @Id 

    
    @Column(name="companyId", unique=true, nullable=false)
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="location", length=45)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="latitude", length=45)
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="altitude", length=45)
    public String getAltitude() {
        return this.altitude;
    }
    
    public void setAltitude(String altitude) {
        this.altitude = altitude;
    }

    
    @Column(name="founder", length=45)
    public String getFounder() {
        return this.founder;
    }
    
    public void setFounder(String founder) {
        this.founder = founder;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="company")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="company")
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="company")
    public Set<CompanyHasJobrole> getCompanyHasJobroles() {
        return this.companyHasJobroles;
    }
    
    public void setCompanyHasJobroles(Set<CompanyHasJobrole> companyHasJobroles) {
        this.companyHasJobroles = companyHasJobroles;
    }




}


