package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name="function"
    ,catalog="techguy"
)
public class Function  implements java.io.Serializable {


     private Integer functionId;
     private String name;
     private Set<PageFunction> pageFunctions = new HashSet<PageFunction>(0);

    public Function() {
    }

    public Function(String name, Set<PageFunction> pageFunctions) {
       this.name = name;
       this.pageFunctions = pageFunctions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="function_id", unique=true, nullable=false)
    public Integer getFunctionId() {
        return this.functionId;
    }
    
    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="function")
    public Set<PageFunction> getPageFunctions() {
        return this.pageFunctions;
    }
    
    public void setPageFunctions(Set<PageFunction> pageFunctions) {
        this.pageFunctions = pageFunctions;
    }




}


