package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Interviewdescription generated by hbm2java
 */
@Entity
@Table(name="interviewdescription"
    ,catalog="techguy"
)
public class Interviewdescription  implements java.io.Serializable {


     private Integer interviewDescId;
     private Interview interview;
     private String question;

    public Interviewdescription() {
    }

	
    public Interviewdescription(Interview interview) {
        this.interview = interview;
    }
    public Interviewdescription(Interview interview, String question) {
       this.interview = interview;
       this.question = question;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="interviewDescId", unique=true, nullable=false)
    public Integer getInterviewDescId() {
        return this.interviewDescId;
    }
    
    public void setInterviewDescId(Integer interviewDescId) {
        this.interviewDescId = interviewDescId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Interview_interviewId", nullable=false)
    public Interview getInterview() {
        return this.interview;
    }
    
    public void setInterview(Interview interview) {
        this.interview = interview;
    }

    
    @Column(name="question", length=45)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }




}


