package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobrole generated by hbm2java
 */
@Entity
@Table(name="jobrole"
    ,catalog="techguy"
)
public class Jobrole  implements java.io.Serializable {


     private Integer jobRoleId;
     private String name;
     private String permanent;
     private Set<User> users = new HashSet<User>(0);
     private Set<CompanyHasJobrole> companyHasJobroles = new HashSet<CompanyHasJobrole>(0);

    public Jobrole() {
    }

    public Jobrole(String name, String permanent, Set<User> users, Set<CompanyHasJobrole> companyHasJobroles) {
       this.name = name;
       this.permanent = permanent;
       this.users = users;
       this.companyHasJobroles = companyHasJobroles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jobRoleId", unique=true, nullable=false)
    public Integer getJobRoleId() {
        return this.jobRoleId;
    }
    
    public void setJobRoleId(Integer jobRoleId) {
        this.jobRoleId = jobRoleId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="permanent", length=4)
    public String getPermanent() {
        return this.permanent;
    }
    
    public void setPermanent(String permanent) {
        this.permanent = permanent;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jobrole")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jobrole")
    public Set<CompanyHasJobrole> getCompanyHasJobroles() {
        return this.companyHasJobroles;
    }
    
    public void setCompanyHasJobroles(Set<CompanyHasJobrole> companyHasJobroles) {
        this.companyHasJobroles = companyHasJobroles;
    }




}


