package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name="privilege"
    ,catalog="techguy"
)
public class Privilege  implements java.io.Serializable {


     private Integer privilegeId;
     private PageFunction pageFunction;
     private Role role;

    public Privilege() {
    }

    public Privilege(PageFunction pageFunction, Role role) {
       this.pageFunction = pageFunction;
       this.role = role;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="privilege_id", unique=true, nullable=false)
    public Integer getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="page_function_page_func_id", nullable=false)
    public PageFunction getPageFunction() {
        return this.pageFunction;
    }
    
    public void setPageFunction(PageFunction pageFunction) {
        this.pageFunction = pageFunction;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_roleid", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


