package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name="project"
    ,catalog="techguy"
)
public class Project  implements java.io.Serializable {


     private Long projectId;
     private Cvdata cvdata;
     private String projectName;
     private String description;
     private Date durationFrom;
     private Date durationTo;
     private Set<Technology> technologies = new HashSet<Technology>(0);

    public Project() {
    }

	
    public Project(Cvdata cvdata) {
        this.cvdata = cvdata;
    }
    public Project(Cvdata cvdata, String projectName, String description, Date durationFrom, Date durationTo, Set<Technology> technologies) {
       this.cvdata = cvdata;
       this.projectName = projectName;
       this.description = description;
       this.durationFrom = durationFrom;
       this.durationTo = durationTo;
       this.technologies = technologies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="projectId", unique=true, nullable=false)
    public Long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CVData_cvDataId", nullable=false)
    public Cvdata getCvdata() {
        return this.cvdata;
    }
    
    public void setCvdata(Cvdata cvdata) {
        this.cvdata = cvdata;
    }

    
    @Column(name="projectName", length=45)
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    
    @Column(name="description", length=80)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="durationFrom", length=10)
    public Date getDurationFrom() {
        return this.durationFrom;
    }
    
    public void setDurationFrom(Date durationFrom) {
        this.durationFrom = durationFrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="durationTo", length=10)
    public Date getDurationTo() {
        return this.durationTo;
    }
    
    public void setDurationTo(Date durationTo) {
        this.durationTo = durationTo;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="technology_has_project", catalog="techguy", joinColumns = { 
        @JoinColumn(name="Project_projectId", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Technology_technologyId", nullable=false, updatable=false) })
    public Set<Technology> getTechnologies() {
        return this.technologies;
    }
    
    public void setTechnologies(Set<Technology> technologies) {
        this.technologies = technologies;
    }




}


