package com.techguy.application.model;
// Generated Jan 3, 2019 9:27:06 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;




/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="techguy"
)
public class User  implements java.io.Serializable {

     private int userId;
     private Company company;
     private Cvdata cvdata;
     private Jobrole jobrole;
     private Role role;
     private String userName;
     private String firstname;
     private String lastName;
     private String gender;
     private Integer age;
     private String email;
     private String telephone;
     private String addressLineOne;
     private String addressLineTwo;
     private String city;
     private String cityCode;
     private String province;
     private String country;
     private String password;
     private String proPicture;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Boolean enabled;
     private String confirmationToken;

    public User() {
    }

	
    public User(int userId, Company company, Cvdata cvdata, Jobrole jobrole, Role role, String userName, String password , Boolean enabled , String confirmationToken) {
        this.userId = userId;
        this.company = company;
        this.cvdata = cvdata;
        this.jobrole = jobrole;
        this.role = role;
        this.userName = userName;
        this.password = password;
        this.enabled = enabled;
        this.confirmationToken = confirmationToken;
    }
    public User(int userId, Company company, Cvdata cvdata, Jobrole jobrole, Role role, String userName, String firstname, String lastName, String gender, Integer age, String email, String telephone, String addressLineOne, String addressLineTwo, String city, String cityCode, String province, String country, String password, String proPicture, Set<Review> reviews ,  Boolean enabled , String confirmationToken) {
       this.userId = userId;
       this.company = company;
       this.cvdata = cvdata;
       this.jobrole = jobrole;
       this.role = role;
       this.userName = userName;
       this.firstname = firstname;
       this.lastName = lastName;
       this.gender = gender;
       this.age = age;
       this.email = email;
       this.telephone = telephone;
       this.addressLineOne = addressLineOne;
       this.addressLineTwo = addressLineTwo;
       this.city = city;
       this.cityCode = cityCode;
       this.province = province;
       this.country = country;
       this.password = password;
       this.proPicture = proPicture;
       this.reviews = reviews;
       this.enabled = enabled;
       this.confirmationToken = confirmationToken;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="userId",nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_companyId")
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CVData_cvDataId")
    public Cvdata getCvdata() {
        return this.cvdata;
    }
    
    public void setCvdata(Cvdata cvdata) {
        this.cvdata = cvdata;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JobRole_jobRoleId")
    public Jobrole getJobrole() {
        return this.jobrole;
    }
    
    public void setJobrole(Jobrole jobrole) {
        this.jobrole = jobrole;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_roleid")
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    
    @Column(name="userName", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="firstname", length=255)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastName", length=255)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="gender", length=255)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    
    @Column(name="email", length=255 , unique = true)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telephone", length=255)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="addressLineOne", length=255)
    public String getAddressLineOne() {
        return this.addressLineOne;
    }
    
    public void setAddressLineOne(String addressLineOne) {
        this.addressLineOne = addressLineOne;
    }

    
    @Column(name="addressLineTwo", length=255)
    public String getAddressLineTwo() {
        return this.addressLineTwo;
    }
    
    public void setAddressLineTwo(String addressLineTwo) {
        this.addressLineTwo = addressLineTwo;
    }

    
    @Column(name="city", length=255)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="cityCode", length=255)
    public String getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    
    @Column(name="province", length=255)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    
    @Column(name="country", length=255)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="password", nullable=false, length=255)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="proPicture", length=255)
    public String getProPicture() {
        return this.proPicture;
    }
    
    public void setProPicture(String proPicture) {
        this.proPicture = proPicture;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

    @Column(name="enabled", length=255)
	public Boolean getEnabled() {
		return enabled;
	}


	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	 @Column(name="confirmationToken", length=255)
	public String getConfirmationToken() {
		return confirmationToken;
	}


	public void setConfirmationToken(String confirmationToken) {
		this.confirmationToken = confirmationToken;
	}




}


